app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, PasswordField, RadioField
from wtforms.validators import DataRequired, EqualTo, Length


class Login(FlaskForm):
    account = StringField(u'账号', validators=[DataRequired()])
    password = PasswordField(u'密码', validators=[DataRequired()])
    submit = SubmitField(u'登录')


class Logon(FlaskForm):
    account = StringField(u'账号', validators=[DataRequired(), Length(6, 32)])
    password1 = PasswordField(u'输入密码', validators=[DataRequired(), Length(4, 32)])
    password2 = PasswordField(u'确认密码', validators=[DataRequired(), Length(4, 32)])
    level = StringField(u'输入等级：管理员 or 普通用户', validators=[DataRequired(), Length(3, 4)])
    name = StringField(u'你的名字', validators=[DataRequired(), Length(1, 64)])
    submit = SubmitField(u'注册')


class SearchBookForm(FlaskForm):
    methods = [('book_name', '书名'), ('author', '作者'), ('class_name', '类别'), ('isbn', 'ISBN')]
    method = SelectField(choices=methods, validators=[DataRequired()], coerce=str)
    content = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class StoreForm(FlaskForm):
    barcode = StringField(validators=[DataRequired(), Length(6)])
    isbn = StringField(validators=[DataRequired(), Length(13)])
    location = StringField(validators=[DataRequired(), Length(1, 32)])
    submit = SubmitField(u'提交')


class BookDelete(FlaskForm):
    isbn = StringField(validators=[DataRequired(), Length(13)])
    book_name = StringField(validators=[DataRequired(), Length(1, 64)])
    submit = SubmitField(u'提交')


class NewStoreForm(FlaskForm):
    isbn = StringField(validators=[DataRequired(), Length(13)])
    book_name = StringField(validators=[DataRequired(), Length(1, 64)])
    press = StringField(validators=[DataRequired(), Length(1, 32)])
    author = StringField(validators=[DataRequired(), Length(1, 64)])
    class_name = StringField(validators=[DataRequired(), Length(1, 64)])
    book_location = StringField(validators=[DataRequired(), Length(1, 64)])
    store_count = StringField(validators=[DataRequired(), Length(1, 10)])
    submit = SubmitField(u'提交')


class UpdateStoreForm(FlaskForm):
    isbn = StringField(validators=[DataRequired(), Length(13)])
    book_name = StringField(validators=[DataRequired(), Length(1, 64)])
    press = StringField(validators=[DataRequired(), Length(1, 32)])
    author = StringField(validators=[DataRequired(), Length(1, 64)])
    class_name = StringField(validators=[DataRequired(), Length(1, 64)])
    book_location = StringField(validators=[DataRequired(), Length(1, 64)])
    store_count = StringField(validators=[DataRequired(), Length(1, 10)])
    loan_count = StringField(validators=[DataRequired(), Length(1, 10)])
    submit = SubmitField(u'提交')


class BorrowForm(FlaskForm):
    card = StringField(validators=[DataRequired()])
    book_name = StringField(validators=[DataRequired()])
    submit = SubmitField(u'搜索')


class SearchStudentForm(FlaskForm):
    card = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class ChangeUserInfo(FlaskForm):
    admin_name = StringField(u'你的名字',validators=[DataRequired(), Length(1, 64)])
    sex = StringField(u'男/女', validators=[DataRequired(), Length(1, 2)])
    telephone = StringField(u'联系电话', validators=[DataRequired(), Length(11)])
    submit = SubmitField('保存')

class BookBookForm(FlaskForm):
    book_name = StringField(validators=[DataRequired()])
    submit = SubmitField(u'搜索')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from . import main
from .forms import Login, Logon, SearchBookForm, StoreForm, NewStoreForm, UpdateStoreForm, BorrowForm, \
    SearchStudentForm, BookDelete, ChangeUserInfo, BookBookForm
from ..models import Admin, Student, Book, Inventory, ReadBook
from .. import db
from flask import flash, redirect, url_for, session, render_template, request, jsonify
from flask_login import login_user, logout_user, login_required, current_user
import time
from datetime import datetime, date


# ******************************* 注册登录相关 *******************************

@main.route('/', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        user = Admin.query.filter_by(admin_id=form.account.data, password=form.password.data).first()
        user_2 = Student.query.filter_by(card_id=form.account.data, password=form.password.data).first()
        if user is None and user_2 is None:
            flash(u'用户名或密码错误，请重新输入')
            return redirect(url_for('.login'))  # 蓝图跳转
        else:
            if user is not None:
                login_user(user)
                print("login------>", user)
                session['admin_id'] = user.admin_id
                session['name'] = user.admin_name
                session['right'] = '最高管理功能'
                session['group'] = 'admin'
                current_user.right = session['right']
                current_user.group = session['group']


            else:
                login_user(user_2)
                print("login------>", user_2)
                session['admin_id'] = user_2.card_id
                session['name'] = user_2.admin_name
                session['right'] = '编辑个人信息 查询/预定图书'
                session['group'] = 'student'
                current_user.right = session['right']
                current_user.group = session['group']
                current_user.sex = user_2.sex
                current_user.telephone = user_2.telephone
                current_user.enroll_date = user_2.enroll_date
                current_user.valid_date = user_2.valid_date

            print(session['name'], session['admin_id'])
            return redirect(url_for('main.index'))
    return render_template('main/login.html', form=form)


@main.route("/logon", methods=['GET', 'POST'])
def logon():
    form = Logon()
    if form.validate_on_submit():
        if form.password1.data != form.password2.data:
            flash(u"请确认密码是否保持一致！")
        else:
            if form.level.data == '管理员':
                user = Admin(form.account.data, form.name.data, form.password1.data, form.level.data)
                db.session.add(user)
                db.session.commit()
            elif form.level.data == "普通用户":
                card_id = form.account.data
                today_date = date.today()
                today_str = today_date.strftime("%Y-%m-%d")
                today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
                valid_date = (int(today_stamp) + 365 * 4 * 86400) * 1000
                user = Student(card_id, form.account.data, form.password1.data, form.name.data, '男', '12300000000',
                               today_stamp, valid_date, False, False)
                db.session.add(user)
                db.session.commit()
            else:
                flash(u'请正确输入等级！')
                return redirect(url_for('.logon'))

            flash(u'注册成功，请登录！')
            return redirect(url_for('.login'))
    return render_template('main/logon.html', form=form)


@main.route('/index', methods=['GET', 'POST'])
def index():
    form = SearchBookForm()
    return render_template('main/index.html', form=form)


@main.route('/user/<id>')
@login_required
def user_info(id):
    user = Admin.query.filter_by(admin_id=id).first()
    if user is None:
        user = Student.query.filter_by(admin_id=id).first()
    return render_template('main/user-info.html', user=user, name=session.get('name'))


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已经登出！')
    return redirect(url_for('.login'))


# ******************************* 查找书籍 *******************************

@main.route('/search_book', methods=['GET', 'POST'])
@login_required
def search_book():  # 这个函数里不再处理提交按钮，使用Ajax局部刷新
    form = SearchBookForm()
    return render_template('main/search-book.html', name=session.get('name'), form=form)


@main.route('/books', methods=['POST'])
def find_book():
    def find_name():
        return Book.query.filter(Book.book_name.like('%' + request.form.get('content') + '%')).all()

    def find_author():
        return Book.query.filter(Book.author.contains(request.form.get('content'))).all()

    def find_class():
        return Book.query.filter(Book.class_name.contains(request.form.get('content'))).all()

    def find_isbn():
        return Book.query.filter(Book.isbn.contains(request.form.get('content'))).all()

    def find_book_location():
        return Book.query.filter(Book.book_location.contains(request.form.get('content'))).all()

    def find_book_store_count():
        return Book.query.filter(Book.store_count.contains(request.form.get('content'))).all()

    methods = {
        'book_name': find_name,
        'author': find_author,
        'class_name': find_class,
        'isbn': find_isbn,
        'book_location': find_book_location,
        'store_count': find_book_store_count
    }
    books = methods[request.form.get('method')]()
    data = []
    for book in books:
        count = Inventory.query.filter_by(isbn=book.isbn).count()
        available = Inventory.query.filter_by(isbn=book.isbn, status=True).count()
        # count = str(book.store_count)
        # available = str(int(book.store_count) - int(book.loan_count))
        item = {'isbn': book.isbn, 'book_name': book.book_name, 'press': book.press, 'author': book.author,
                'class_name': book.class_name, 'book_location': book.book_location, 'count': count,
                'available': available}
        if book.withdraw is False:
            data.append(item)
    return jsonify(data)


# ******************************* 添加新书 *******************************

@main.route('/storage', methods=['GET', 'POST'])
@login_required
def storage():
    form = StoreForm()
    if session['group'] == 'student':
        flash(u'您无权限操作！')
    if form.validate_on_submit():
        if session['group'] == 'student':
            flash(u'您无权限操作！')
            return redirect(url_for('.storage'))
        book = Book.query.filter_by(isbn=request.form.get('isbn')).first()
        exist = Inventory.query.filter_by(barcode=request.form.get('barcode')).first()
        if book is None:
            flash(u'添加失败，请注意本书信息是否已录入，若未登记，请在‘新书入库’窗口录入信息。')
        else:
            if len(request.form.get('barcode')) != 6:
                flash(u'图书编码长度错误')
            else:
                if exist is not None:
                    flash(u'该编号已经存在！')
                else:
                    item = Inventory()
                    item.barcode = request.form.get('barcode')
                    item.isbn = request.form.get('isbn')
                    item.admin = current_user.admin_id
                    item.location = request.form.get('location')
                    item.status = True
                    item.withdraw = False
                    today_date = datetime.date.today()
                    today_str = today_date.strftime("%Y-%m-%d")
                    today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
                    item.storage_date = int(today_stamp) * 1000
                    db.session.add(item)
                    db.session.commit()
                    flash(u'入库成功！')
        return redirect(url_for('.storage'))
    return render_template('main/storage.html', name=session.get('name'), form=form)


@main.route('/new_store', methods=['GET', 'POST'])
@login_required
def new_store():
    form = NewStoreForm()
    if session['group'] == 'student':
        flash(u'您无权限操作！')
    if form.validate_on_submit():
        if session['group'] == 'student':
            flash(u'您无权限操作！')
            return redirect(url_for('.new_store'))
        if len(request.form.get('isbn')) != 13:
            flash(u'ISBN长度错误')
        else:
            exist = Book.query.filter_by(isbn=request.form.get('isbn')).first()
            if exist is not None:
                flash(u'该图书信息已经存在，请核对后再录入；或者填写入库表。')
            else:
                book = Book()
                book.isbn = request.form.get('isbn')
                book.book_name = request.form.get('book_name')
                book.press = request.form.get('press')
                book.author = request.form.get('author')
                book.class_name = request.form.get('class_name')
                book.book_location = request.form.get('book_location')
                book.store_count = request.form.get('store_count')
                book.loan_count = 0
                db.session.add(book)
                db.session.commit()

                for i in range(int(book.store_count)):
                    print(i)
                    inventory = Inventory()
                    inventory.barcode = str(book.isbn + '_' + str(i))[-6:]
                    inventory.isbn = book.isbn
                    inventory.admin = current_user.admin_id
                    print(current_user.admin_id)
                    inventory.location = book.book_location
                    inventory.status = True
                    inventory.withdraw = False
                    today_date = date.today()
                    today_str = today_date.strftime("%Y-%m-%d")
                    today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
                    inventory.storage_date = today_stamp
                    db.session.add(inventory)
                db.session.commit()

                flash(u'图书信息添加成功！')
        return redirect(url_for('.new_store'))

app/templates/main/base-user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="../static/layui/css/layui.css">
    <link rel="stylesheet" href="../static/login.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <style>
          .alert{position:relative;padding:.75rem 1.25rem;margin-bottom:1rem;border:1px solid transparent;border-radius:.25rem}
          .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
          .alert-warning{color:#856404;background-color:#fff3cd;border-color:#ffeeba}
          .close{float:right;font-size:1.5rem;font-weight:700;line-height:1;color:#000;text-shadow:0 1px 0 #fff;opacity:.5}
          .close:focus,.close:hover{color:#000;text-decoration:none;opacity:.75}
          .close:not(:disabled):not(.disabled){cursor:pointer}
          button.close{padding:0;background-color:transparent;border:0;-webkit-appearance:none}
          .close{padding:1rem;margin:-1rem -1rem -1rem auto}
          .alert-dismissible .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
    </style>
</head>
<body>
<div class="layui-layout layui-layout-admin">
<div class="layui-header layui-bg-molv">
  <div class="layui-logo"><span style="color:#F0F0F0;font-size: large">图书管理系统</span></div>
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item"><a class="aa" href="{{ url_for('main.login') }}">登录</a></li>
      <li class="layui-nav-item"><a class="aa" href="{{ url_for('main.logon') }}">注册</a></li>
    </ul>
  </div>
</div>
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
    </div>
{% endfor %}
</div>

{% block body %}
{% endblock %}

<script src="../static/layui/layui.js"></script>
<script type="text/javascript">
    layui.use('form', function () {
        var form = layui.form;

    });
</script>
{% block script %}{% endblock %}
</body>
</html>

app/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="../static/layui/css/layui.css">
  <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
  <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <style>
      .alert{position:relative;padding:.75rem 1.25rem;margin-bottom:1rem;border:1px solid transparent;border-radius:.25rem}
      .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
      .alert-warning{color:#856404;background-color:#fff3cd;border-color:#ffeeba}
      .close{float:right;font-size:1.5rem;font-weight:700;line-height:1;color:#000;text-shadow:0 1px 0 #fff;opacity:.5}
      .close:focus,.close:hover{color:#000;text-decoration:none;opacity:.75}
      .close:not(:disabled):not(.disabled){cursor:pointer}
      button.close{padding:0;background-color:transparent;border:0;-webkit-appearance:none}
      .close{padding:1rem;margin:-1rem -1rem -1rem auto}
      .alert-dismissible .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
  </style>
  {% block head %}{% endblock %}
  <style>{% block style %}{% endblock %}</style>
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <a href="{{ url_for('main.index') }}"><div class="layui-logo">图书管理系统</div></a>
    <!-- 头部区域（可配合layui已有的水平导航） -->
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item">
        <a href="javascript:;">
          <img src="../static/icon.jpg" class="layui-nav-img">
          {{ name }}
        </a>
        <dl class="layui-nav-child">
          <dd><a href="{{ url_for('main.user_info', id=current_user.admin_id) }}">个人信息</a></dd>
        </dl>
      </li>
      <li class="layui-nav-item"><a href="{{ url_for('main.logout') }}">退出登录</a></li>
    </ul>
  </div>

  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree"  lay-filter="test">
        <li class="layui-nav-item">
          <a class="" href="javascript:;">普通用户功能</a>
          <dl class="layui-nav-child">
             <dd><a href="{{ url_for('main.search_book') }}">图书查询</a></dd>
              <dd><a href="{{ url_for('main.book_book') }}">图书预订</a></dd>
              <dd><a href="{{ url_for('main.change_user_info') }}">个人信息管理</a></dd>
           </dl>
        </li>
        <li class="layui-nav-item">
          <a href="javascript:;">管理员功能</a>
          <dl class="layui-nav-child">
              <dd><a href="{{ url_for('main.search_student') }}">学生信息查询</a></dd>
             <dd><a href="{{ url_for('main.borrow') }}">登记借书</a></dd>
             <dd><a href="{{ url_for('main.return_book') }}">登记还书</a></dd>
             <dd><a href="{{ url_for('main.new_store') }}">图书入库</a></dd>
             <dd><a href="{{ url_for('main.update_store') }}">图书管理</a></dd>
          </dl>
        </li>

      </ul>
    </div>
  </div>

  <div class="layui-body">
    <!-- 内容主体区域 -->
    <div class="layui-card layui-row layui-col-space10" style="margin:15px 10px;width:100%;">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
        </div>
        {% endfor %}
        {% block card %}{% endblock %}
        <div class="layui-card-body">
        {% block body %}
        {% endblock %}
        </div>
    </div>
  </div>

  <div class="layui-footer">
    软工大作业-图书管理系统
  </div>
</div>
<script src="../static/layui/layui.js"></script>
<script>

layui.use('element', function(){
  var element = layui.element;
  element.init();


});
</script>

{% block script %}

{% endblock %}

</body>
</html>

app/templates/main/delete-book.html
{% extends 'main/base.html' %}
{% block title %}图书管理{% endblock %}

{% block card %}
<div class="layui-card-header">
    <h2>图书删除</h2>

</div>
{% endblock %}
{% block body %}
<form class="layui-form" method="post">
    {{ form.csrf_token }}
    <div class="layui-form-item" style="height: 50px;">
        <label class="layui-form-label" style="font-size: medium">ISBN：</label>
        <div class="layui-input-block">
            {{ form.isbn(class="layui-input", style="width:40%") }}
        </div>
    </div>
    <div class="layui-form-item" style="height: 50px;">
        <label class="layui-form-label" style="font-size: medium">书名：</label>
        <div class="layui-input-block">
            {{ form.book_name(class="layui-input", style="width:40%") }}
        </div>
    </div>
    <div class="layui-form-item" style="height: 50px;">
        <div class="layui-input-block">
            {{ form.submit(class="layui-btn", style="width:100px;font-size:medium") }}
        </div>
    </div>
</form>
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}首页{% endblock %}\

{% block body %}
<div style="width: 1200px;margin: auto">
    <br/>
    <form class="layui-form" method="post" id="searchForm">
        {{ form.csrf_token }}
        <div class="layui-form-item">
            <div class="layui-inline">
                <div class="layui-row layui-col-space10">
                    <div class="layui-col-md4">
                        {{ form.method(class="layui-input-inline") }}
                    </div>
                    <div class="layui-col-md6">
                        <label class="layui-form-label">查询内容：</label>
                        <div class="layui-input-inline">
                            {{ form.content(class="layui-input",style="width:250px") }}
                        </div>
                    </div>
                    <div class="layui-col-md2">
                        <div class="layui-input-inline">{{ form.submit(class="layui-btn", id="search") }}</div>

                    </div>
                </div>
            </div>

        </div>
    </form>
    <div id="remove">
        <table lay-even id="result" lay-filter="re">
            <thead>
            <tr>
                <th lay-data="{field:'isbn', width:140}">ISBN</th>
                <th lay-data="{field:'book_name', width:200}">书名</th>
                <th lay-data="{field:'press', width:180}">出版社</th>
                <th lay-data="{field:'author', width:140}">作者</th>
                <th lay-data="{field:'class_name', width:200}">类别</th>
                <th lay-data="{field:'book_location', width:200}">位置</th>
                <th lay-data="{field:'count', width:120}">馆藏数量</th>
                <th lay-data="{field:'available'}">可借数量</th>
            </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
    <table id="test" lay-filter="test"></table>
</div>
{% endblock %}

{% block script %}
<script>
    layui.use(['form', 'table', 'jquery'], function () {
        var form = layui.form;
        var table = layui.table;
        var $ = layui.$;

        table.init('re', {
            height: 390
            , limit: 7
            , page: true
        });

        $(document).ready(function () {
            $('#search').on('click', function () {
                var form = new FormData(document.getElementById("searchForm"));
                if ($('#content').val() === "") {
                    layui.use('layer', function () {
                        var layer = layui.layer;

                        layer.msg('请填写查询内容', {time: 800});
                    });
                } else {
                    $.ajax({
                        url: "{{ url_for('main.find_book') }}",
                        type: "post",
                        data: form,
                        processData: false,
                        contentType: false,
                        success: function (data) {
                            if (data.length !== 0) {
                                $('#remove').remove();
                                table.render({
                                    elem: '#test'
                                    , data: data
                                    , cols: [[
                                        {field: 'isbn', title: 'ISBN', width: 140}
                                        , {field: 'book_name', title: '书名', width: 200}
                                        , {field: 'press', title: '出版社', width: 180}
                                        , {field: 'author', title: '作者', width: 140}
                                        , {field: 'class_name', title: '类别', width: 200}
                                        , {field: 'book_location', title: '位置', width: 200}
                                        , {field: 'count', title: '馆藏数量', width: 120}
                                        , {field: 'available', title: '可借数量'}
                                    ]]
                                    , page: true
                                    , height: 390
                                    , limit: 7
                                    , response: {
                                        statusCode: 200 //重新规定成功的状态码为 200，table 组件默认为 0
                                    }
                                    , parseData: function (data) { //将原始数据解析成 table 组件所规定的数据
                                        return {
                                            "code": data.status, //解析接口状态
                                            "msg": data.message, //解析提示文本
                                            "count": data.total, //解析数据长度
                                            "data": data.rows.item //解析数据列表
                                        };
                                    }
                                });
                            } else {
                                layui.use('layer', function () {
                                    var layer = layui.layer;

                                    layer.msg('未找到任何结果', {time: 1000});
                                });
                            }
                        }
                    });
                }
                return false;
            })
        });

    });
</script>
{% endblock %}

app/templates/main/search-book.html
{% extends "main/base.html" %}
{% block title %}查询图书信息{% endblock %}

{% block card %}
<div class="layui-card-header"><h2>查询图书信息</h2></div>{% endblock %}
{% block body %}
<form class="layui-form" method="post" id="searchForm">
    {{ form.csrf_token }}
    <div class="layui-form-item">
        <div class="layui-inline">
            <div class="layui-row layui-col-space10">
                <div class="layui-col-md4">
                    {{ form.method(class="layui-input-inline") }}
                </div>
                <div class="layui-col-md6">
                    <label class="layui-form-label">查询内容：</label>
                    <div class="layui-input-inline">
                        {{ form.content(class="layui-input",style="width:250px") }}
                    </div>
                </div>
                <div class="layui-col-md2">
                    <div class="layui-input-inline">{{ form.submit(class="layui-btn", id="search") }}</div>

                </div>
            </div>
        </div>

    </div>
</form>
<div id="remove">
    <table lay-even id="result" lay-filter="re">
        <thead>
        <tr>
            <th lay-data="{field:'isbn', width:140}">ISBN</th>
            <th lay-data="{field:'book_name', width:200}">书名</th>
            <th lay-data="{field:'press', width:180}">出版社</th>
            <th lay-data="{field:'author', width:140}">作者</th>
            <th lay-data="{field:'class_name', width:200}">类别</th>
            <th lay-data="{field:'book_location', width:200}">位置</th>
            <th lay-data="{field:'count', width:120}">馆藏数量</th>
            <th lay-data="{field:'available'}">可借数量</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<table id="test" lay-filter="test"></table>

{% endblock %}

{% block script %}
<script>
    layui.use(['form', 'table', 'jquery'], function () {
        var form = layui.form;
        var table = layui.table;
        var $ = layui.$;

        table.init('re', {
            height: 390
            , limit: 7
            , page: true
        });

        $(document).ready(function () {
            $('#search').on('click', function () {
                var form = new FormData(document.getElementById("searchForm"));
                if ($('#content').val() === "") {
                    layui.use('layer', function () {
                        var layer = layui.layer;

                        layer.msg('请填写查询内容', {time: 800});
                    });
                } else {
                    $.ajax({
                        url: "{{ url_for('main.find_book') }}",
                        type: "post",
                        data: form,
                        processData: false,
                        contentType: false,
                        success: function (data) {
                            if (data.length !== 0) {
                                $('#remove').remove();
                                table.render({
                                    elem: '#test'
                                    , data: data
                                    , cols: [[
                                        {field: 'isbn', title: 'ISBN', width: 140}
                                        , {field: 'book_name', title: '书名', width: 200}
                                        , {field: 'press', title: '出版社', width: 180}
                                        , {field: 'author', title: '作者', width: 140}
                                        , {field: 'class_name', title: '类别', width: 200}
                                        , {field: 'book_location', title: '位置', width: 200}
                                        , {field: 'count', title: '馆藏数量', width: 120}
                                        , {field: 'available', title: '可借数量'}
                                    ]]
                                    , page: true
                                    , height: 390
                                    , limit: 7
                                    , response: {
                                        statusCode: 200 //重新规定成功的状态码为 200，table 组件默认为 0
                                    }
                                    , parseData: function (data) { //将原始数据解析成 table 组件所规定的数据
                                        return {
                                            "code": data.status, //解析接口状态
                                            "msg": data.message, //解析提示文本
                                            "count": data.total, //解析数据长度
                                            "data": data.rows.item //解析数据列表
                                        };
                                    }
                                });
                            } else {
                                layui.use('layer', function () {
                                    var layer = layui.layer;

                                    layer.msg('未找到任何结果', {time: 1000});
                                });
                            }
                        }
                    });
                }
                return false;
            })
        });

    });
</script>
{% endblock %}